### ISSUE TITLE
Could you change its license to more lose one?

### ISSUE THREAD

**Issue by insikk** [mete0r/pyhwp#153]
I think AGPL is so strict. It is even more strict than GPL. I was considering to make another open source project, because it cannot be used in any commercial purpose without being open sourced. However you made great work. So I want to use your work or even contribute to it. 

If you change it to LGPL or MIT licenses, many developer will use it, and this project may be maintained by community more actively. Also you are the single contributor, and whole decision is up to you. By changing to lesser license, you could get help from community for all the jobs of license transition.

**Comment by ethus3h** [comment]
LGPL/MIT/etc. just let companies take advantage of libre software to make their own non-libre software: in general, they do not benefit the libre software community when used for original software, and are mainly useful to encourage commercial companies to release their code as libre software (since then they get to take the community's improvements and use them in other proprietary software, it provides an incentive for releasing the code). AGPL3 does let you use the code, as long as you release your code under a compatible license, which is great — it helps grow the libre software ecosystem!

Barring exceptional circumstances, I strongly advise against relicensing libre software under a weaker license.

P.S.: I am not a lawyer.

**Comment by mete0r** [comment]
두 분 모두 의견 감사드립니다.

pyhwp 는 아직 개념증명 수준 단계의 프로그램이라 생각합니다. 내부의 골간 구조는 물론 출력 형식마저 유동적이고, 따라서 dependable 하거나 contributable 한 수준이 되려면 갈 길이 멉니다. 그 전까지는 사용허가조건 변경이나 구성요소의 별도 프로젝트 분리 등은 고려하기 어렵다는 점 부디 이해 바랍니다.

해가 바뀌었으니 올해는 조금이라도 진전을 볼 계획입니다.
